### ISSUE TITLE
Chicken has eye problem in Android

### ISSUE THREAD

**Issue by hugows** [ggomaeng/react-native-svg-chicken#1]
Unfortunately! 

![screenshot_20170322-082642-1080x1920](https://cloud.githubusercontent.com/assets/11545/24195692/7ec6c9a2-0ed9-11e7-928e-77f07287b64b.png)

**Comment by dk0r** [comment]
There are a lot of problems here (i.e. feet/feathers/tail/wing --not just the eye)

**Comment by ggomaeng** [comment]
Thanks for raising the issue guys--React native for Android seems to have many bugs that haven't been resolved yet. I feel like there is nothing I can do here, but if anyone can guide me in the right direction, I would appreciate it!
